### ISSUE TITLE
String index out of range

### ISSUE THREAD

**Issue by NewAstronaut7451** [francoisforster/gedcom-cleanup#1]
I get the message

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source)
        at Event.matches(Event.kt:18)
        at GedcomCompare.matchIndividualScore(GedcomCompare.kt:358)
        at GedcomCompare.matchFamilyScore(GedcomCompare.kt:345)
        at GedcomCompare.access$matchFamilyScore(GedcomCompare.kt:7)
        at GedcomCompare$compareFamilies$matchedFamilies$1.invoke(GedcomCompare.kt:209)
        at GedcomCompare$compareFamilies$matchedFamilies$1.invoke(GedcomCompare.kt:7)
        at GedcomCompare.pairAndScoreRecord(GedcomCompare.kt:319)
        at GedcomCompare.matchRecords(GedcomCompare.kt:272)
        at GedcomCompare.compareFamilies(GedcomCompare.kt:209)
        at GedcomCompare.compareIndividuals(GedcomCompare.kt:140)
        at GedcomCompare.compareIndividuals(GedcomCompare.kt:60)
        at GedcomCompare.compareFrom(GedcomCompare.kt:28)
        at GedcomComparisonKt.main(GedcomComparison.kt:24)

when trying to run this on multiple files.

**Comment by francoisforster** [comment]
Hello, please try again. I've made a fix: https://github.com/francoisforster/gedcom-cleanup/commit/24142b2e7fda0604a74db33660f566e4107a2915
